config/routes.rb
Rails.application.routes.draw do
  
  get 'welcome/index'

  devise_for :users
  resources :users, only: [:show, :index]
  resources :shoes
  

  root 'welcome#index'

end

app/models/shoes.rb
class Shoes < ActiveRecord::Base
	belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

    has_many :shoes
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shoes_controller.rb
class ShoesController < ApplicationController
  def new
  	@shoe = Shoes.new
  end

  def index
  	@shoe = Shoes.all
  end

  def edit
  end

  def show
  end

  def destroy
    @shoe.destroy 
    end
 

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shoe
      @shoe = shoe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def shoe_params
      params.fetch(:product, {})
    end
 end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shoes_helper.rb
module ShoesHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
      <%= link_to "Shoes!", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
      	<li><%= link_to "Shoes", shoes_path, class: "navbar-brand" %></li>
      	</ul> 
        <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu ">
                <li><%= link_to "Profile", user_path(current_user.id)%></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

             <li role="separator" class="divider"></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                
              </ul>
            </li>
            <% else %>

            <li><%= link_to "Log In", new_user_session_path %></li>

        <% end %>
          </ul>
       
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
		<p class="notice"><%= notice %></p>
      	<p class="alert"><%= alert %></p>
<head>
  <title>Shoeapp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
	<%= render 'layouts/header' %>

<%= yield %>

</body>
</html>

app/views/shoes/_form.html.erb
<%= simple_form_for(@shoes) do |f| %>
  <%= f.error_notification %>

<div class="container">
  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :size %>
    <%= f.input :designer %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>

   <div class="hidden">
  <%= f.number_field :user_id, value: current_user.id %>
  </div>
  
<% end %>
</div>

app/views/shoes/edit.html.erb
<h1>Shoes#edit</h1>
<p>Find me in app/views/shoes/edit.html.erb</p>

app/views/shoes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Shoes</h1>

<table>
  <thead>
    <tr>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @shoe.each do |shoe| %>
      <tr>
        <td><%= shoe.entry %></td>
        <td><%= link_to 'Show', shoe %></td>
        <td><%= link_to 'Edit', edit_shoe_path(shoe) %></td>
        <td><%= link_to 'Destroy', shoe, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>

      <%= render 'shoes/form' %>

    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Shoe', new_shoe_path %>

app/views/shoes/new.html.erb
<h1>Shoes#new</h1>
<p>Find me in app/views/shoes/new.html.erb</p>

app/views/shoes/show.html.erb
<h1>Shoes#show</h1>
<p>Find me in app/views/shoes/show.html.erb</p>

app/views/welcome/_header.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
     
      <%= link_to "Shoes!", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Shoes", shoes_path, class: "navbar-brand" %></li>
        </ul> 
        <ul class="nav navbar-nav navbar-right">

        <% if current_user %>
            <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><%= current_user.email %> <span class="caret"></span></a>
              <ul class="dropdown-menu ">
                <li><%= link_to "Profile", user_path(current_user.id)%></li>
                <li><%= link_to "Settings", edit_user_registration_path %></li>
            <li role="separator" class="divider"></li>
            <li><a href="#">Separated link</a></li>

             <li role="separator" class="divider"></li>
                <li><%= link_to "Log Out", destroy_user_session_path, method: :delete %></li>
                
              </ul>
            </li>
            <% else %>

            <li><%= link_to "Log In", new_user_session_path %></li>

        <% end %>
          </ul>
       
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

app/views/welcome/index.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Shoes!</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>	

<%= yield %>

</body>
</html>